# Default values for rives-node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

dapp:
  configMapName: dapp-deployment

image:
  repository: cartesi/rollups-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.4.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

redis:
  endpoint: "redis://redis:6379"

blockchain:
  create: true
  secretName: anvil-secret

  id: 31337
  http_endpoint: http://anvil:8545
  ws_endpoint: ws://anvil:8545
  is_legacy: false
  genesis_block: 1
  finality_offset: 1
  block_timeout: 60


postgres:
  secretName: database-credentials

graphql_server:
  # GraphQL Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Cartesi GraphQL Server expected environment variables
  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info
  graphql_host: "0.0.0.0"
  graphql_port: 8000
  graphql_healthcheck_port: 8001

indexer:
  # GraphQL Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthcheck_port: 8001

  # Cartesi Indexer expected environment variables
  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info

authority:
  # GraphQL Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Cartesi Authority Claimer expected environment variables
  walletSecretName: authority-wallet

  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info
  http_port: 8000

state_server:
  # GraphQL Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  port: 8000

  # Cartesi Indexer expected environment variables
  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info
  concurrent_events_fetch: 1

dispatcher:
  # GraphQL Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  http_port: 8000

  # Cartesi Indexer expected environment variables
  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info
  epoch_blocks: 7200

server_manager:
  # Server Manager pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  port: 8000

  # Server Manager expected environment variables
  log_level: debug
  cartesi_machine_log_level: info
  snapshot_dir: /usr/share/rollups-node/snapshot
  snapshot_storage_size: 2Gi
  snapshot_storage_class: standard
  seed_image_dir: /tmp/machine-snapshots/0_0

inspect:
  # Inspect Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  http_port: 8000
  healthcheck_port: 8001

  # Inspect Server Environment Variables
  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info
  session_id: default_session_id

advance_runner:
  # Inspect Server pod parameters
  replicaCount: 1
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthcheck_port: 8001

  # Inspect Server Environment Variables
  log_enable_timestamp: "false"
  log_enable_color: "false"
  rust_log: info
  session_id: default_session_id
  deadline_checkin: null # default: 5*1000 (ms?)
  deadline_advance_state: null # default: 3 * 60 * 1000 (ms)
  deadline_inspect_state: null # default: 3 * 60 * 1000 (ms)
  deadline_machine: null # default: 5 * 60 * 1000 (ms)
  deadline_fast: null # default: 5 * 1000 (ms)

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
