{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reader-node.serviceAccountName" . }}
  labels:
    {{- include "reader-node.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "reader-node.serviceAccountName" . }}-permissioned-controller
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reader-node.serviceAccountName" . }}-permissioned-controller
subjects:
- kind: ServiceAccount
  name: {{ include "reader-node.serviceAccountName" . }}
roleRef:
  kind: Role
  name: permissioned-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
