{{- if .Values.blockchain.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.blockchain.secretName }}
  labels:
    {{- include "rives-node.labels" . | nindent 4 }}
type: Opaque
stringData:
  id: "{{ .Values.blockchain.id }}"
  http_endpoint: "{{ .Values.blockchain.http_endpoint }}"
  ws_endpoint: "{{ .Values.blockchain.ws_endpoint }}"
  is_legacy: "{{ .Values.blockchain.is_legacy }}"
  genesis_block: "{{ .Values.blockchain.genesis_block }}"
  finality_offset: "{{ .Values.blockchain.finality_offset }}"
  block_timeout: "{{ .Values.blockchain.block_timeout }}"
{{- end }}
