apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rives-node.fullname" . }}-graphql
  labels:
    {{- include "rives-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.graphql_server.replicaCount }}
  selector:
    matchLabels:
      {{- include "rives-node.selectorLabels" . | nindent 6 }}
      app.kubernets.io/component: graphql
  template:
    metadata:
      {{- with .Values.graphql_server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rives-node.selectorLabels" . | nindent 8 }}
        app.kubernets.io/component: graphql
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: graphql-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - "/usr/bin/cartesi-rollups-graphql-server"

          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_PORT

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_DB

            - name: POSTGRES_ENDPOINT
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"

            - name: LOG_ENABLE_TIMESTAMP
              value: "{{ .Values.graphql_server.log_enable_timestamp }}"

            - name: LOG_ENABLE_COLOR
              value: "{{ .Values.graphql_server.log_enable_color }}"

            - name: RUST_LOG
              value: {{ .Values.graphql_server.rust_log }}

            - name: GRAPHQL_HOST
              value: {{ .Values.graphql_server.graphql_host }}

            - name: GRAPHQL_PORT
              value: "{{ .Values.graphql_server.graphql_port }}"

            - name: GRAPHQL_HEALTHCHECK_PORT
              value: "{{ .Values.graphql_server.graphql_healthcheck_port }}"

          ports:
            - name: http
              containerPort: {{ .Values.graphql_server.graphql_port }}
              protocol: TCP
            - name: healthcheck
              containerPort: {{ .Values.graphql_server.graphql_healthcheck_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.graphql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.graphql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rives-node.fullname" . }}-graphql
  labels:
    {{- include "rives-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.graphql_server.graphql_port }}
      targetPort: http
      protocol: TCP
      name: http

    - port: {{ .Values.graphql_server.graphql_healthcheck_port }}
      targetPort: healthcheck
      protocol: TCP
      name: healthcheck

  selector:
    {{- include "rives-node.selectorLabels" . | nindent 4 }}
    app.kubernets.io/component: graphql


