apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rives-node.fullname" . }}-indexer
  labels:
    {{- include "rives-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.indexer.replicaCount }}
  selector:
    matchLabels:
      {{- include "rives-node.selectorLabels" . | nindent 6 }}
      app.kubernets.io/component: indexer
  template:
    metadata:
      {{- with .Values.indexer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rives-node.selectorLabels" . | nindent 8 }}
        app.kubernets.io/component: indexer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: indexer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command:
            - "/usr/bin/cartesi-rollups-indexer"

          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_HOST

            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_PORT

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_DB

            - name: POSTGRES_ENDPOINT
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"

            - name: LOG_ENABLE_TIMESTAMP
              value: "{{ .Values.indexer.log_enable_timestamp }}"

            - name: LOG_ENABLE_COLOR
              value: "{{ .Values.indexer.log_enable_color }}"

            - name: RUST_LOG
              value: {{ .Values.indexer.rust_log }}

            - name: REDIS_ENDPOINT
              value: {{ .Values.redis.endpoint }}

            - name: INDEXER_HEALTHCHECK_PORT
              value: "{{ .Values.indexer.healthcheck_port }}"

            - name: CHAIN_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.blockchain.secretName }}
                  key: id

            - name: DAPP_CONTRACT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.dapp.configMapName }}
                  key: dapp_address

          ports:
            - name: healthcheck
              containerPort: {{ .Values.indexer.healthcheck_port }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
          readinessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
          resources:
            {{- toYaml .Values.indexer.resources | nindent 12 }}

      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rives-node.fullname" . }}-indexer
  labels:
    {{- include "rives-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.indexer.healthcheck_port }}
      targetPort: healthcheck
      protocol: TCP
      name: healthcheck

  selector:
    {{- include "rives-node.selectorLabels" . | nindent 4 }}
    app.kubernets.io/component: indexer


